
# Post \#66373169 [Link](https://stackoverflow.com/questions/66373169/)

## Tensorflow 2 Object Detection API: Numpy Version Errors

**Vote**: 11 (370/702) **Views**: 6457 (494/702) 

**Internal ID** \#1-3-234

Created at 2021-02-25 17:07:18

Tags: `python-3.x` `numpy` `object-detection-api`

----------

#### Metadata:

Area: `Data Science & Machine Learning`

Language: `python` (full parsed tag list: `python`)

----------

**Notepad**


----------

I followed the "Training Custom Object Detector" tutorial ([https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html))
When running the script to continue training a pre-trained model:
`python model_main_tf2.py --model_dir=models/my_ssd_resnet50_v1_fpn --pipeline_config_path=models/my_ssd_resnet50_v1_fpn/pipeline.config`
(found here: [https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py))
, I get the following errors.
Scenario #1:
- - 
`NotImplementedError: Cannot convert a symbolic Tensor (cond_2/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported`
I looked online and it suggests to downgrade the numpy version < 1.20.0 ([NotImplementedError: Cannot convert a symbolic Tensor (2nd_target:0) to a numpy array](https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy)). Note, the version numpy version must be >= 1.19.2 for tensorflow 2.2.0.
Scenario #2:
- - 
`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject`
However, the online recommendation is to upgrade numpy to >= 1.20.0. ([ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp)). There is a github issue related to this: [https://github.com/tensorflow/models/issues/9749](https://github.com/tensorflow/models/issues/9749).
I'm not sure what version to use to get the code running.

```
File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 104, in main
    model_lib_v2.train_loop(
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\model_lib_v2.py", line 530, in train_loop
    train_input = strategy.experimental_distribute_datasets_from_function(
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\util\deprecation.py", line 340, in new_func
    return func(*args, **kwargs)
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1143, in experimental_distribute_datasets_from_function
    return self.distribute_datasets_from_function(dataset_fn, options)
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1134, in distribute_datasets_from_function
    return self._extended._distribute_datasets_from_function(  # pylint: disable=protected-access
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\mirrored_strategy.py", line 545, in _distribute_datasets_from_function
    return input_lib.get_distributed_datasets_from_function(
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\input_lib.py", line 161, in get_distributed_datasets_from_function
    return DistributedDatasetsFromFunction(dataset_fn, input_workers,
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\input_lib.py", line 1272, in __init__
    _create_datasets_from_function_with_input_context(
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\input_lib.py", line 1936, in _create_datasets_from_function_with_input_context
    dataset = dataset_fn(ctx)
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\model_lib_v2.py", line 521, in train_dataset_fn
    train_input = inputs.train_input(
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\inputs.py", line 893, in train_input
    dataset = INPUT_BUILDER_UTIL_MAP['dataset_build'](
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\builders\dataset_builder.py", line 251, in build
    dataset = dataset_map_fn(dataset, decoder.decode, batch_size,
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\builders\dataset_builder.py", line 236, in dataset_map_fn
    dataset = dataset.map_with_legacy_function(
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\util\deprecation.py", line 340, in new_func
    return func(*args, **kwargs)
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2679, in map_with_legacy_function
    ParallelMapDataset(
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 4242, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3493, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\function.py", line 546, in add_to_graph
    self._create_definition_if_needed()
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\function.py", line 378, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\function.py", line 400, in _create_definition_if_needed_impl
    temp_graph = func_graph_from_py_func(
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\function.py", line 971, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3485, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3453, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\autograph\impl\api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NotImplementedError: in user code:

    C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\data_decoders\tf_example_decoder.py:524 default_groundtruth_weights  *
        [tf.shape(tensor_dict[fields.InputDataFields.groundtruth_boxes])[0]],
    C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\util\dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\array_ops.py:3120 ones
        output = _constant_if_small(one, shape, dtype, name)
    C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\ops\array_ops.py:2804 _constant_if_small
        if np.prod(shape) < 1000:
    <__array_function__ internals>:5 prod

    C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\numpy\core\fromnumeric.py:3030 prod
        return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
    C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\numpy\core\fromnumeric.py:87 _wrapreduction
        return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
    C:\Users\212765830\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\ops.py:852 __array__
        raise NotImplementedError(
NotImplementedError: Cannot convert a symbolic Tensor (cond_2/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```


```
2021-02-25 09:59:47.039105: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-02-25 09:59:47.044310: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "model_main_tf2.py", line 32, in <module>
    from object_detection import model_lib_v2
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\model_lib_v2.py", line 29, in <module>
    from object_detection import eval_util
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\eval_util.py", line 35, in <module>
    from object_detection.metrics import coco_evaluation
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\metrics\coco_evaluation.py", line 25, in <module>
    from object_detection.metrics import coco_tools
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\object_detection\metrics\coco_tools.py", line 51, in <module>
    from pycocotools import coco
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\pycocotools\coco.py", line 56, in <module>
    from . import mask as maskUtils
  File "C:\Users\212765830\AppData\Local\Continuum\anaconda3\envs\tensorflow\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject```
```



----------
        
## GPT4 Attempt \#0

The errors you're encountering are due to incompatibilities between different versions of TensorFlow, NumPy, and possibly other libraries. Here are some steps you can take to resolve these issues:

1. **Create a new virtual environment**: This is generally a good practice to avoid conflicts between different projects that may require different versions of the same libraries. You can use `conda` or `virtualenv` to create a new environment.

2. **Install the correct versions of the libraries**: TensorFlow 2.2.0 requires NumPy version >=1.16.0 and <1.19.0. So, you can try installing NumPy 1.18.5 which is the latest version in this range. You can do this with the following command:

    ```
    pip install numpy==1.18.5
    ```

3. **Reinstall TensorFlow**: After installing the correct version of NumPy, reinstall TensorFlow 2.2.0 with the following command:

    ```
    pip install tensorflow==2.2.0
    ```

4. **Reinstall pycocotools**: The second error you're encountering is related to the `pycocotools` library. You can try reinstalling it with the following command:

    ```
    pip install pycocotools
    ```

5. **Check other dependencies**: Make sure that other libraries required by your project are installed and their versions are compatible with TensorFlow 2.2.0.

After following these steps, try running your script again. If you still encounter errors, please provide the full error messages and I'll be glad to help you further.

--------

## GPT4 Attempt \#1

The errors you are encountering are due to the incompatibility between TensorFlow and NumPy versions. TensorFlow 2.2.0 requires NumPy version >= 1.19.2 but < 1.20.0. However, the latest versions of some other packages may require NumPy version >= 1.20.0.

Here are some steps you can try to resolve the issue:

1. Create a new Python virtual environment. This is to ensure that the changes you make do not affect your other projects. You can use `venv` module which is included in standard Python library to create a virtual environment:

    ```
    python -m venv myenv
    ```

    To activate the virtual environment:

    - On Windows:

        ```
        .\myenv\Scripts\activate
        ```

    - On Unix or MacOS:

        ```
        source myenv/bin/activate
        ```

2. Install TensorFlow 2.2.0 in the virtual environment:

    ```
    pip install tensorflow==2.2.0
    ```

3. Install the correct version of NumPy:

    ```
    pip install numpy==1.19.5
    ```

    This version should work with TensorFlow 2.2.0 and also resolve the `numpy.ndarray size changed` error.

4. Install other required packages. Make sure to install the versions that are compatible with TensorFlow 2.2.0 and NumPy 1.19.5.

5. Run your script again.

Remember to activate the virtual environment every time you work on this project. If you still encounter errors, they might be due to other packages. In that case, you will need to find the versions that are compatible with both TensorFlow 2.2.0 and NumPy 1.19.5.

--------

## GPT4 Attempt \#2

The errors you're encountering are due to incompatibility between TensorFlow and Numpy versions. TensorFlow 2.2.0 requires Numpy version >=1.19.2 and <1.20.0. However, the error `numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject` is usually encountered when using Numpy version <1.20.0.

Here are a few steps you can try to solve these issues:

1. **Create a new virtual environment**: This is to ensure that there are no conflicts with other installed packages. You can use `conda` or `virtualenv` to create a new environment.

2. **Install the correct versions of TensorFlow and Numpy**: After creating the new environment, install TensorFlow 2.2.0 and Numpy 1.19.5. You can do this using pip:

    ```bash
    pip install tensorflow==2.2.0
    pip install numpy==1.19.5
    ```

3. **Reinstall pycocotools**: The error `numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject` is related to the `pycocotools` package. After installing the correct versions of TensorFlow and Numpy, reinstall `pycocotools`:

    ```bash
    pip uninstall pycocotools
    pip install pycocotools
    ```

4. **Run your script again**: After following the above steps, try running your script again. If you're still encountering errors, please provide the full error message and I'll be happy to assist you further.

--------
